# Generated by Django 4.1.3 on 2024-02-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect_emails', '0004_remove_customsupporter_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomSupporter',
            new_name='Supporter',
        ),
    ]
